FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

ENV CI=true \
    PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

CMD ["npm", "test"]
