"use client";
import {FormEvent,useState} from "react";
export default function EnquiryForm({division}:{division:"it"|"overseas"}){
 const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;setLoading(true);setMessage("");const f=new FormData(formElement);const payload={division,name:f.get("name"),email:f.get("email"),phone:f.get("phone"),subject:f.get("subject"),message:f.get("message"),source:"website"};const r=await fetch("/api/v1/public/enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setLoading(false);setMessage(r.ok?"Thank you. Your enquiry has been received and the relevant EduSphere team will follow up.":"We could not submit your enquiry. Please review the fields and try again.");if(r.ok)formElement.reset()}
 // Every field has a real id/htmlFor pairing -- PUB-001/PUB-002 both claim "accessible
 // labels" in MASTER_FEATURE_CATALOG.md, but the inherited markup only ever placed a
 // <label> next to its <input> as unlinked siblings (no programmatic association for
 // assistive tech). Fixed here rather than just noted, since this is this feature's own
 // stated requirement, not a different feature's concern.
 return <form className="form" onSubmit={submit}><div className="form-grid"><div className="field"><label htmlFor={`${division}-enquiry-name`}>Full name *</label><input id={`${division}-enquiry-name`} name="name" required/></div><div className="field"><label htmlFor={`${division}-enquiry-email`}>Email *</label><input id={`${division}-enquiry-email`} name="email" type="email" required/></div></div><div className="form-grid"><div className="field"><label htmlFor={`${division}-enquiry-phone`}>Phone</label><input id={`${division}-enquiry-phone`} name="phone" type="tel"/></div><div className="field"><label htmlFor={`${division}-enquiry-subject`}>{division==="it"?"Programme / hiring need":"Destination / study interest"} *</label><input id={`${division}-enquiry-subject`} name="subject" required/></div></div><div className="field"><label htmlFor={`${division}-enquiry-message`}>How can we help? *</label><textarea id={`${division}-enquiry-message`} name="message" required/></div><button className="btn" disabled={loading}>{loading?"Submitting…":division==="it"?"Request training callback":"Book counseling callback"}</button>{message&&<div className={message.startsWith("Thank")?"form-message":"form-error"} role="status" aria-live="polite">{message}</div>}</form>
}
