"use client";
import Link from "next/link"; import Image from "next/image"; import {usePathname, useRouter} from "next/navigation"; import type {NavItem} from "@/lib/navigation"; import PortalMobileNav from "./PortalMobileNav"; import {Suspense} from "react"; import NavGroup from "./NavGroup";
// RESPONSIVE_RULES.md baseline rule (NFR-RESP-001, CONFIRMED_CURRENT): "Primary action
// always reachable without horizontal scroll... collapses behind a toggle" -- below
// 640px this sidebar used to become a fixed bottom bar with `.portal-nav{overflow:auto}`
// (horizontal scroll, no visible affordance that more items existed off-screen: a
// Trainer's own 9-item nav truncated mid-word at "Mate[rials]" with no scrollbar/fade
// hint). Confirmed directly against the running app (tester feedback 2026-09-04, WhatsApp,
// RAID.md I-15) before fixing. Replaced with the exact same toggle+dropdown pattern
// already proven for the public site's own mobile nav (MobileNavToggle, built for
// FRONTEND_ANALYSIS.md #4.1) instead of inventing a new interaction -- see globals.css's
// `@media(max-width:640px)` block for the CSS side of this swap.
// AGN-017 (DEC-SCOPE-059 N8): an item's unread count -- in the link's name as text (" unread" is visually hidden), never colour alone.
const badgeText=(n:number)=>n>99?"99+":String(n);
// QA17-05: below 980 px the sidebar collapses into the menu, so the top bar also links the first counted item (CSS shows it there only).
function TopbarUnread({nav}:{nav:NavItem[]}){const item=nav.find(x=>x.badge);if(!item?.badge)return null;return <Link className="badge topbar-unread" href={item.href}>{badgeText(item.badge)}<span className="visually-hidden"> unread {item.label.toLowerCase()}</span></Link>}
export default function PortalShell({children,nav,roleLabel,userName,studentCode}:{children:React.ReactNode;nav:NavItem[];roleLabel:string;userName:string;studentCode?:string|null}){const router=useRouter();const pathname=usePathname();async function logout(){await fetch("/api/v1/auth/logout",{method:"POST"});router.push("/");router.refresh()}return <div className="portal"><aside className="sidebar"><Link href="/"><Image className="sidebar-logo logo-on-dark" src="/brand/logo-dark.png" width={420} height={140} alt="EduSphere"/></Link><div className="role-pill"><strong>{roleLabel}</strong><br/>{userName}{studentCode&&<><br/><span style={{fontSize:12,opacity:0.85}}>Student ID: {studentCode}</span></>}</div><nav className="portal-nav">{nav.map(x=>x.children?.length?<Suspense key={x.href} fallback={<Link href={x.href}>{x.label}</Link>}><NavGroup item={x} pathname={pathname}/></Suspense>:<Link key={x.href} href={x.href} aria-current={pathname===x.href?"page":undefined}>{x.label}{x.badge?<> <span className="badge nav-badge">{badgeText(x.badge)}<span className="visually-hidden"> unread</span></span></>:null}</Link>)}</nav><div className="sidebar-footer" style={{display:"grid",gap:10,justifyItems:"start"}}><Link className="btn ghost small" style={{color:"white",borderColor:"#45668e"}} href="/account/password">Change password</Link><Link className="btn ghost small" style={{color:"white",borderColor:"#45668e"}} href="/account/profile">My profile</Link><button className="btn ghost small" style={{color:"white",borderColor:"#45668e"}} onClick={logout}>Sign out</button></div></aside><main className="portal-main"><div className="portal-topbar"><strong>EduSphere Portal</strong><div style={{display:"flex",alignItems:"center",gap:12,minWidth:0}}>{/* bdm-010 re-test: a long name truncates so the badge and menu stay on a 320 px screen */}<span className="muted" title={userName} style={{minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{userName}</span><TopbarUnread nav={nav}/><PortalMobileNav nav={[{href:"/account/password",label:"Change password"},{href:"/account/profile",label:"My profile"},...nav.flatMap(x=>[{href:x.href,label:x.badge?`${x.label} (${badgeText(x.badge)} unread)`:x.label},...(x.children??[]).filter(c=>c.href!==x.href/* AGN-018 QA18-02: an "All" child repeats its parent -- one link, one current */).map(c=>({href:c.href,label:`${x.label}: ${c.label}`}))])]}/></div></div>{children}</main></div>}
