import {notFound} from "next/navigation";import { accessUnavailable } from "./AccessUnavailable";import AgentApplicationsSection from "./AgentApplicationsSection";import AgentStudentsSection from "./AgentStudentsSection";import PortalShell from "./PortalShell";import PortalSection from "./PortalSection";import RefreshOnHistoryNav from "./RefreshOnHistoryNav";import TeacherWorkspaceActions from "./TeacherWorkspaceActions";import WorkflowPanel from "./WorkflowPanel";import {ApiError,serverApi} from "@/lib/api";import {agentNavFor,PORTAL_NAV} from "@/lib/navigation";import type {PortalPayload,User} from "@/lib/types";
const labels:Record<string,string>={"it/student":"IT Student","it/trainer":"Trainer","it/placement":"Placement Team","it/hr":"HR / Employer","it/admin":"IT Administrator","overseas/student":"Overseas Student","overseas/counselor":"Counselor","overseas/university":"University Representative","overseas/agent":"Education Agent","overseas/admin":"Overseas Administrator"};
export default async function PortalPage({division,role,section}:{division:"it"|"overseas";role:string;section:string}){const key=`${division}/${role}`;const nav=PORTAL_NAV[key]||[];if(!nav.some(item=>item.href===`/${division}/${role}/${section}`))notFound();// AGN-008 QA8-09: the agency Applications page reads its own API (AgentApplicationsSection). The portal payload is still fetched
// as the page's role/approval gate (403 for a wrong role or a pending/rejected agent); only its 404 "Workspace not found" is held
// back there, and only a Super Admin then gets the section (its note) -- anyone else still gets the access-unavailable card.
const agentApplications=key==="overseas/agent"&&section==="applications";
let user:User;let data:PortalPayload|null;try{[user,data]=await Promise.all([serverApi<User>("/api/v1/auth/me"),serverApi<PortalPayload>(`/api/v1/portal/${division}/${role}/${section}`).catch((e)=>{if(agentApplications&&e instanceof ApiError&&e.status===404)return null;throw e})])}catch(e){return accessUnavailable(e, `/${division}/login`)}
if(!data&&user.role!=="super_admin")return accessUnavailable(new ApiError("Workspace not found",404), `/${division}/login`);const teacherWorkspace=division==="it"&&role==="trainer";
// AGN-002: an agency's staff see no Team/Commissions links; the full `nav` above still admits a typed URL, so the server's 403 card shows.
const agent=key==="overseas/agent";
// AGN-004 browser QA-01/02: the agency Students page leads with every student (with or without a login), full width; the
// AGT-002 roster below is retitled as what it is -- application status of the students who have a login.
// AGN-008: the agency Applications page is the applications panel (list, detail, filters); the generic table is replaced there only.
const main=agentApplications?<AgentApplicationsSection user={user}/>:!data?null:agent&&section==="students"?<>
<AgentStudentsSection user={user}/>
<PortalSection data={{...data,title:"Application status",subtitle:"Students who have a login, with each one's current application (AGT-002)."}}/>
</>:<PortalSection data={data}/>;
return <PortalShell nav={agent?agentNavFor(nav,user.agent_member_role,user.agent_permissions):nav} roleLabel={agent&&user.agent_member_role==="staff"?"Agency Staff":labels[key]||role} userName={user.full_name} studentCode={role==="student"?user.student_code:null}>{/* AGN-003 browser QA-07: Back/Forward re-asks the server, so revoked permissions apply. */}{agent&&<RefreshOnHistoryNav/>}{main}{teacherWorkspace?<TeacherWorkspaceActions section={section}/>:<WorkflowPanel user={user} section={section}/>}</PortalShell>}
