"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

function detail(value:unknown){if(typeof value==="string")return value;if(Array.isArray(value))return value.map((item:{msg?:string})=>item.msg||"Invalid input").join("; ");return "Registration failed."}

// AGN-001 (E2): an education agent may name their agency; blank falls back to their full name on the server.
export default function RegisterForm({division}:{division:"it"|"overseas"}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[accountType,setAccountType]=useState("student");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const agency=String(form.get("agency_name")||"").trim();const body={full_name:form.get("full_name"),email:form.get("email"),phone:form.get("phone")||null,password:form.get("password"),division,account_type:accountType,...(accountType==="agent"&&agency?{agency_name:agency}:{})};const response=await fetch("/api/v1/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(detail(data.detail));return}router.push(data.user.role==="agent"?"/overseas/agent/dashboard":division==="it"?"/it/student/dashboard":"/overseas/student/dashboard");router.refresh()}
  return <form className="form" onSubmit={submit}><div className="field"><label htmlFor="reg-full-name">Full name</label><input id="reg-full-name" name="full_name" autoComplete="name" required/></div><div className="field"><label htmlFor="reg-email">Email</label><input id="reg-email" name="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="reg-phone">Phone</label><input id="reg-phone" name="phone" type="tel" autoComplete="tel"/></div>{division==="overseas"&&<div className="field"><label htmlFor="reg-account-type">Account type</label><select id="reg-account-type" name="account_type" value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="student">Student</option><option value="agent">Education agent</option></select></div>}{division==="overseas"&&accountType==="agent"&&<div className="field"><label htmlFor="reg-agency-name">Agency name (optional)</label><input id="reg-agency-name" name="agency_name" maxLength={160} autoComplete="organization"/></div>}<div className="field"><label htmlFor="reg-password">Password</label><input id="reg-password" name="password" type="password" minLength={10} autoComplete="new-password" required/><span className="muted" style={{fontSize:12}}>Use at least 10 characters.</span></div>{message&&<div className="form-error" role="alert">{message}</div>}<button className="btn" disabled={busy}>{busy?"Creating account…":"Create account"}</button></form>
}
