"""upc-025 (spec MP12/MP13): build apps/web/lib/worldMapShapes.ts from Natural Earth's 1:50m Admin 0 countries (public domain).

Run once by hand; the output is committed, so the app has no map dependency and downloads nothing:

    curl -o ne.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
    python scripts/build_world_map.py ne.geojson

Equirectangular projection of latitude 84 N to 60 S onto a 2000 x 800 view box (so Antarctica is not drawn), integer coordinates and
relative path steps to keep the file small. Countries are keyed by ISO_A2_EH (it fills NE's "-99" codes for France, Norway and Kosovo).
A country whose largest polygon spans less than SMALL view-box units in both directions is flagged `small` and gets a marker at NE's
label point (Singapore, Malta, Bahrain, ...)."""

import json
import sys
from pathlib import Path

WIDTH, HEIGHT, NORTH, SOUTH = 2000, 800, 84.0, -60.0
SMALL = 12  # view-box units, about 6 px on a 1000 px wide map
MIN_RING = 1.5  # islands smaller than this in both directions are dropped (except a country's largest polygon)
OUT = Path(__file__).resolve().parent.parent / "apps" / "web" / "lib" / "worldMapShapes.ts"


def project(lon: float, lat: float) -> tuple[int, int]:
    lat = max(SOUTH, min(NORTH, lat))
    return round((lon + 180) / 360 * WIDTH), round((NORTH - lat) / (NORTH - SOUTH) * HEIGHT)


def span(points: list[tuple[int, int]]) -> tuple[int, int]:
    xs, ys = [p[0] for p in points], [p[1] for p in points]
    return max(xs) - min(xs), max(ys) - min(ys)


def ring_path(points: list[tuple[int, int]]) -> str:
    """`m x y` then relative steps, skipping points that project onto the previous one."""
    out, (px, py) = [f"M{points[0][0]} {points[0][1]}l"], points[0]
    steps = []
    for x, y in points[1:]:
        if (x, y) != (px, py):
            steps.append(f"{x - px} {y - py}")
            px, py = x, y
    return out[0] + " ".join(steps).replace(" -", "-") + "z" if steps else ""


def country(feature: dict) -> tuple[str, dict] | None:
    props, geometry = feature["properties"], feature["geometry"]
    code = props.get("ISO_A2_EH") or props.get("ISO_A2")
    if not code or code == "-99" or code == "AQ":
        return None
    polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
    rings = []
    for polygon in polygons:
        outer = [project(lon, lat) for lon, lat in polygon[0]]
        if all(lat < SOUTH for _, lat in polygon[0]):
            continue
        rings.append((span(outer), [outer, *([project(lon, lat) for lon, lat in hole] for hole in polygon[1:])]))
    if not rings:
        return None
    largest = max(rings, key=lambda r: r[0][0] * r[0][1])
    kept = [r for r in rings if r is largest or max(r[0]) >= MIN_RING]
    d = "".join(ring_path(ring) for _, group in kept for ring in group)
    x, y = project(props["LABEL_X"], props["LABEL_Y"])
    return code, {"d": d, "x": x, "y": y, "small": max(largest[0]) < SMALL}


def main(source: str) -> None:
    features = json.loads(Path(source).read_bytes().decode("utf-8"))["features"]
    shapes: dict[str, dict] = {}
    for code, shape in filter(None, (country(f) for f in features)):
        if code in shapes:  # a code split over several features: one path, the first feature's label point
            print(f"merged a second {code} feature")
            shapes[code] = shapes[code] | {"d": shapes[code]["d"] + shape["d"], "small": shapes[code]["small"] and shape["small"]}
        else:
            shapes[code] = shape
    shapes = dict(sorted(shapes.items()))
    lines = [
        "// upc-025 -- generated by scripts/build_world_map.py from Natural Earth 1:50m Admin 0 countries (public domain); do not edit.",
        f'export const VIEW_BOX = "0 0 {WIDTH} {HEIGHT}";',
        "export type Shape = { d: string; x: number; y: number; small: boolean };",
        "export const SHAPES: Record<string, Shape> = {",
        *(f'  {code}: {{ d: "{s["d"]}", x: {s["x"]}, y: {s["y"]}, small: {str(s["small"]).lower()} }},' for code, s in shapes.items()),
        "};",
        "",
    ]
    OUT.write_bytes("\n".join(lines).encode("utf-8"))
    print(f"{len(shapes)} countries, {OUT.stat().st_size // 1024} KB, small: {', '.join(c for c, s in shapes.items() if s['small'])}")


if __name__ == "__main__":
    main(sys.argv[1])
